/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dmessage.proto */

#ifndef PROTOBUF_C_dmessage_2eproto__INCLUDED
#define PROTOBUF_C_dmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ReqGetSlotInfo ReqGetSlotInfo;
typedef struct _ReqGetSlotList ReqGetSlotList;
typedef struct _DMessage DMessage;


/* --- enums --- */


/* --- messages --- */

struct  _ReqGetSlotInfo
{
  ProtobufCMessage base;
  uint32_t slotid;
};
#define REQ_GET_SLOT_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&req_get_slot_info__descriptor) \
    , 0 }


struct  _ReqGetSlotList
{
  ProtobufCMessage base;
  protobuf_c_boolean tokenpresent;
  uint32_t ulcount;
};
#define REQ_GET_SLOT_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&req_get_slot_list__descriptor) \
    , 0, 0 }


struct  _DMessage
{
  ProtobufCMessage base;
  uint64_t code;
  ReqGetSlotInfo *getslotinfo;
  ReqGetSlotList *getslotlist;
};
#define DMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dmessage__descriptor) \
    , 0, NULL, NULL }


/* ReqGetSlotInfo methods */
void   req_get_slot_info__init
                     (ReqGetSlotInfo         *message);
size_t req_get_slot_info__get_packed_size
                     (const ReqGetSlotInfo   *message);
size_t req_get_slot_info__pack
                     (const ReqGetSlotInfo   *message,
                      uint8_t             *out);
size_t req_get_slot_info__pack_to_buffer
                     (const ReqGetSlotInfo   *message,
                      ProtobufCBuffer     *buffer);
ReqGetSlotInfo *
       req_get_slot_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   req_get_slot_info__free_unpacked
                     (ReqGetSlotInfo *message,
                      ProtobufCAllocator *allocator);
/* ReqGetSlotList methods */
void   req_get_slot_list__init
                     (ReqGetSlotList         *message);
size_t req_get_slot_list__get_packed_size
                     (const ReqGetSlotList   *message);
size_t req_get_slot_list__pack
                     (const ReqGetSlotList   *message,
                      uint8_t             *out);
size_t req_get_slot_list__pack_to_buffer
                     (const ReqGetSlotList   *message,
                      ProtobufCBuffer     *buffer);
ReqGetSlotList *
       req_get_slot_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   req_get_slot_list__free_unpacked
                     (ReqGetSlotList *message,
                      ProtobufCAllocator *allocator);
/* DMessage methods */
void   dmessage__init
                     (DMessage         *message);
size_t dmessage__get_packed_size
                     (const DMessage   *message);
size_t dmessage__pack
                     (const DMessage   *message,
                      uint8_t             *out);
size_t dmessage__pack_to_buffer
                     (const DMessage   *message,
                      ProtobufCBuffer     *buffer);
DMessage *
       dmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dmessage__free_unpacked
                     (DMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ReqGetSlotInfo_Closure)
                 (const ReqGetSlotInfo *message,
                  void *closure_data);
typedef void (*ReqGetSlotList_Closure)
                 (const ReqGetSlotList *message,
                  void *closure_data);
typedef void (*DMessage_Closure)
                 (const DMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor req_get_slot_info__descriptor;
extern const ProtobufCMessageDescriptor req_get_slot_list__descriptor;
extern const ProtobufCMessageDescriptor dmessage__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_dmessage_2eproto__INCLUDED */
