/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dmessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dmessage.pb-c.h"
void   req_get_slot_info__init
                     (ReqGetSlotInfo         *message)
{
  static const ReqGetSlotInfo init_value = REQ_GET_SLOT_INFO__INIT;
  *message = init_value;
}
size_t req_get_slot_info__get_packed_size
                     (const ReqGetSlotInfo *message)
{
  assert(message->base.descriptor == &req_get_slot_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_get_slot_info__pack
                     (const ReqGetSlotInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &req_get_slot_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_get_slot_info__pack_to_buffer
                     (const ReqGetSlotInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &req_get_slot_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqGetSlotInfo *
       req_get_slot_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqGetSlotInfo *)
     protobuf_c_message_unpack (&req_get_slot_info__descriptor,
                                allocator, len, data);
}
void   req_get_slot_info__free_unpacked
                     (ReqGetSlotInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &req_get_slot_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   req_get_slot_list__init
                     (ReqGetSlotList         *message)
{
  static const ReqGetSlotList init_value = REQ_GET_SLOT_LIST__INIT;
  *message = init_value;
}
size_t req_get_slot_list__get_packed_size
                     (const ReqGetSlotList *message)
{
  assert(message->base.descriptor == &req_get_slot_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_get_slot_list__pack
                     (const ReqGetSlotList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &req_get_slot_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_get_slot_list__pack_to_buffer
                     (const ReqGetSlotList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &req_get_slot_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqGetSlotList *
       req_get_slot_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqGetSlotList *)
     protobuf_c_message_unpack (&req_get_slot_list__descriptor,
                                allocator, len, data);
}
void   req_get_slot_list__free_unpacked
                     (ReqGetSlotList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &req_get_slot_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dmessage__init
                     (DMessage         *message)
{
  static const DMessage init_value = DMESSAGE__INIT;
  *message = init_value;
}
size_t dmessage__get_packed_size
                     (const DMessage *message)
{
  assert(message->base.descriptor == &dmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dmessage__pack
                     (const DMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dmessage__pack_to_buffer
                     (const DMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DMessage *
       dmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DMessage *)
     protobuf_c_message_unpack (&dmessage__descriptor,
                                allocator, len, data);
}
void   dmessage__free_unpacked
                     (DMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor req_get_slot_info__field_descriptors[1] =
{
  {
    "slotID",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReqGetSlotInfo, slotid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_get_slot_info__field_indices_by_name[] = {
  0,   /* field[0] = slotID */
};
static const ProtobufCIntRange req_get_slot_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor req_get_slot_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "reqGetSlotInfo",
  "ReqGetSlotInfo",
  "ReqGetSlotInfo",
  "",
  sizeof(ReqGetSlotInfo),
  1,
  req_get_slot_info__field_descriptors,
  req_get_slot_info__field_indices_by_name,
  1,  req_get_slot_info__number_ranges,
  (ProtobufCMessageInit) req_get_slot_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor req_get_slot_list__field_descriptors[2] =
{
  {
    "tokenPresent",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ReqGetSlotList, tokenpresent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ulCount",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReqGetSlotList, ulcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_get_slot_list__field_indices_by_name[] = {
  0,   /* field[0] = tokenPresent */
  1,   /* field[1] = ulCount */
};
static const ProtobufCIntRange req_get_slot_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor req_get_slot_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "reqGetSlotList",
  "ReqGetSlotList",
  "ReqGetSlotList",
  "",
  sizeof(ReqGetSlotList),
  2,
  req_get_slot_list__field_descriptors,
  req_get_slot_list__field_indices_by_name,
  1,  req_get_slot_list__number_ranges,
  (ProtobufCMessageInit) req_get_slot_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dmessage__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DMessage, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GetSlotInfo",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DMessage, getslotinfo),
    &req_get_slot_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "GetSlotList",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DMessage, getslotlist),
    &req_get_slot_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dmessage__field_indices_by_name[] = {
  1,   /* field[1] = GetSlotInfo */
  2,   /* field[2] = GetSlotList */
  0,   /* field[0] = code */
};
static const ProtobufCIntRange dmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DMessage",
  "DMessage",
  "DMessage",
  "",
  sizeof(DMessage),
  3,
  dmessage__field_descriptors,
  dmessage__field_indices_by_name,
  1,  dmessage__number_ranges,
  (ProtobufCMessageInit) dmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
